[package]
name = "slimhub"
version = "0.1.0"
edition = "2021"

[dependencies]
slim-common = { path = "../slim-common" }

tokio = { version = "1", features = ["full", "signal"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"

sled = "0.34"
zenoh = "1.9.0"

tracing = "0.1"
tracing-subscriber = "0.3"

hex = "0.4"
chrono = "0.4"
serde_json = "1"
